# Generated by Django 5.0.2 on 2024-03-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_add_to_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='size',
            field=models.CharField(default='', max_length=30),
        ),
    ]
