# Generated by Django 5.0.2 on 2024-03-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='size',
            field=models.CharField(default='', max_length=30),
        ),
    ]
