# Generated by Django 5.0.2 on 2024-03-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
