# Generated by Django 5.0.2 on 2024-03-30 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_order_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contact_no',
        ),
    ]
