# Generated by Django 5.0.2 on 2024-03-30 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='s_name',
        ),
        migrations.AddField(
            model_name='add_product',
            name='s_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sub_category'),
        ),
    ]
