# Generated by Django 5.0.2 on 2024-03-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_add_product_s_name_add_product_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='size',
            field=models.CharField(choices=[('XL', 'XL'), ('M', 'M'), ('L', 'L'), ('S', 'S')], default='', max_length=30),
        ),
    ]
