# Generated by Django 5.0.2 on 2024-03-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_add_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='size',
            field=models.CharField(choices=[('XL', 'XL'), ('M', 'M'), ('L', 'L'), ('S', 'S'), ('free size', 'free size')], default='', max_length=30),
        ),
    ]
